import { useState, useEffect } from 'react';
import Button from './Button';
import styles from './ThemeToggle.module.css';

function ThemeToggle() {
    const [isDark, setIsDark] = useState(false);

    useEffect(() => {
        // Check initial theme
        const isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
        setIsDark(isDarkMode);

        // Sync with any existing forced theme
        if (document.documentElement.classList.contains('force-dark')) {
            setIsDark(true);
        } else if (document.documentElement.classList.contains('force-light')) {
            setIsDark(false);
        }
    }, []);

    const toggleTheme = () => {
        const newTheme = !isDark;
        setIsDark(newTheme);

        const root = document.documentElement;

        if (newTheme) {
            // Force dark mode
            root.classList.add('force-dark');
            root.classList.remove('force-light');
        } else {
            // Force light mode
            root.classList.add('force-light');
            root.classList.remove('force-dark');
        }
    };

    // Returned content and SVG styling generated by DeepSeek
    return (
        <button
            onClick={toggleTheme}
            className={styles.themeToggle}
            aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
            title={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
        >
            {isDark ? (
                // Sun icon for light mode (when currently in dark mode, clicking goes to light)
                <svg
                    className={styles.icon}
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <circle cx="12" cy="12" r="5" stroke="currentColor" strokeWidth="2" fill="none"/>
                    <path d="M12 1V3" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M12 21V23" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M4.22 4.22L5.64 5.64" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M18.36 18.36L19.78 19.78" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M1 12H3" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M21 12H23" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M4.22 19.78L5.64 18.36" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                    <path d="M18.36 5.64L19.78 4.22" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                </svg>
            ) : (
                // Moon icon for dark mode (when currently in light mode, clicking goes to dark)
                <svg
                    className={styles.icon}
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <path
                        d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"
                        stroke="currentColor"
                        strokeWidth="2"
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                </svg>
            )}
        </button>
    );
}

export default ThemeToggle;
